# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0fa4a8bcd6c1548f17e1300f83ae46eb34e192c499d1188a3be538d17e8a9df79b15381882f926f8b61b18b263fc151740fe01b44a80a409943b37547df4fc7a

test:
  secret_key_base: 0e3f1af34c082aa72676110815dbfd78139824821928761f38185481f03c9b1cc2568489935bef2794787e88d2bfeb22584d00314914d472b6f5b8180839f485

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
